project:
  type: book
  output-dir: docs

book:
  title: "Oijee! Andmeteadus"
  author-meta: "Jüri Lillemets"
  date-meta: today
  date-format: iso
  logo: logo.png
  favicon: logo.png
  chapters: 
  - index.qmd
  - part: "Põhimõisted"
    chapters: 
    - andmeteadus.qmd
    - mlaibd.qmd
    - analüüs.qmd
    - tarkvara.qmd
  - part: "R keel"
    chapters: 
    - kasutus.qmd
    - korrastus.qmd
    - joonised.qmd
#    - kraapimine.qmd
  - part: "Statistika"
    chapters:
    - tunnused.qmd
    - valim.qmd
    - valikunihe.qmd
    - taasvalik.qmd
#    - parameetrilisus.qmd
    - seosed.qmd
    - põhjuslikkus.qmd
    - tinglikkus.qmd
    - klassifitseerimine.qmd
    - kaugus.qmd
    - klasterdamine.qmd
    - mõõtmevähendus.qmd
#    - sobitamine.qmd
#    - standardiseerimine.qmd
#    - veatabel.qmd
  - part: "Rakendused"
    chapters:
    - korrelatsioon.qmd
    - seosereeglid.qmd
    - usaldusvahemikud.qmd
    - linreg.qmd
    - logreg.qmd
    - otsusepuu.qmd
    - lähinaabrid.qmd
    - hierarhiline.qmd
    - kkeskmised.qmd
    - peakomponendid.qmd
    - faktoranalüüs.qmd
    - tekstikaeve.qmd
#    - maakaardid.qmd
#    - masinõpe.qmd
  - viited.qmd
#  appendices:
#  - põhimõtted.qmd
#  - sõnastik.qmd

bibliography: ../../notes/assets/library.json
csl: ../../notes/assets/apa.csl

reference-location: margin
format:
  html:
    theme: cosmo
    css: style.css
execute: 
  freeze: auto